login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path('', views.index, name='index'),
    path('success/', views.home, name='home'),
   # path('<int:question_id>/', views.detail, name='detail'),
]

login_page/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('login.urls')),
]

login/models.py
from django.db import models
from passlib.hash import pbkdf2_sha256

class Team(models.Model):
	team = models.CharField(max_length=100, default="")
	user_1 = models.CharField(max_length=100, default = "")
	password_1 = models.CharField(max_length=100, default = "")
	user_2 = models.CharField(max_length=100, default = "")
	password_2 = models.CharField(max_length=100, default = "")
	email = models.EmailField(default = "")
	def __str__(self):
		return self.team
"""
	def verify_password(self, pwd):
		return pbkdf2_sha256.verify(pwd, self.enc_password)"""

login/views.py
from django.shortcuts import render
#from django.views.generic import TemplateView
from passlib.hash import pbkdf2_sha256
from .models import Team

def index(request):
	return render(request, 'login/index.html')

def home(request):
	if request.method == "POST":
		t = Team(team = request.POST['team_1'])
		if t.team == "":
			return render(request, 'login/index.html',  {'error_team_1': " Cannot be empty"})

		t.user_1 = request.POST['user_1']
		if t.user_1 == "":
			return render(request, 'login/index.html',  {'error_user_1': " Cannot be empty"})
		t.password_1 = pbkdf2_sha256.encrypt(str(request.POST['password_1']), rounds=12000, salt_size=32)
		t.user_2 = request.POST['user_2']
		t.password_2 = pbkdf2_sha256.encrypt(str(request.POST['password_2']), rounds=12000, salt_size=32)
		t.email = request.POST['email_1']
		t.save()
	return render(request, 'login/home.html')

login/templates/login/home.html
<h1>Signup successfull</h1>

login/templates/login/index.html
<h1>Login details</h1>

<form action="{% url 'login:home'  %}" method="POST">
	{% csrf_token %}
	<input type="text" placeholder="Enter Team Name" name="team_1"><strong>{{ error_team_1 }}</strong><br>
	<input type="text" placeholder="First user's Name" name="user_1"><strong>{{ error_user_1 }}</strong><br>	
	<input type="password" placeholder="First user's Password" name="password_1"><br>
	<input type="text" placeholder="Second user's Name" name="user_2"><br>	
	<input type="password" placeholder="Second user's Password" name="password_2"><br>
	<input type="email" placeholder="Enter Email" name="email_1"><br>
	<input type="submit" value="submit">
</form>  
</div>